---
title: Test post
author: David Harper
date: '2020-08-20'
slug: test-post
categories:
  - Demo
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2020-08-20T17:47:26-07:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

Let's load some packages...

```{r}
library(tidyverse)
library(magrittr)
library(scales)
library(gridExtra)
library(forecast)
library(tseries)
library(ggthemes)
theme_set(theme_economist())
```

Stationary Time Series: ARMA

Wold Decomposition

arima.sim
model c(p, d, q)
p = AR order
q = MA order

```{r}
# Generate and plot white noise
# WN <- arima.sim(model=list(order= c(0,0,0)), n = 200 )
# plot(WN)

MA_mean = 2
MA_weight = 0.5
# Generate and plot an MA(1) with parameter .9 
# MA <- arima.sim(model=list(order = c(0,0,1), ma = MA_weight), n = 200, mean = MA_mean,
#                rand.gen = rnorm, sd = 40)
MA <- arima.sim(model=list(order = c(0,0,1), ma = MA_weight), n = 200, mean = MA_mean)

AR_param = 0.6
AR_intercept = 3
# Generate and plot an AR(2) with parameters 1.5 and -.75
AR <- arima.sim(model=list(order=c(1,0,0), ar = AR_param), n = 200, mean = AR_intercept)

ts.plot(MA, AR)


```